version: 2.1
parameters:
  GHA_Event:
    type: string
    default: ""
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

jobs:
  release:
    docker:
      - image: cimg/node:lts
    steps:
      - run: npm install
      - run: npm build
      - run: npm publish

  debug:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print pipeline parameters
          command: |
            echo "GHA_Event: << pipeline.parameters.GHA_Event >>"
            echo "GHA_Actor: << pipeline.parameters.GHA_Actor >>"
            echo "GHA_Action: << pipeline.parameters.GHA_Action >>"

workflows:
  release:
    when:
      equal: [ "release", << pipeline.parameters.GHA_Event >>]
    jobs:
      - release

  debug-workflow:
    jobs:
      - debug
