version: 2.1
parameters:
  GHA_Event:
    type: string
    default: ""
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

jobs:
  release:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Simulate install
          command: echo "Installing dependencies..."
      - run:
          name: Simulate build
          command: echo "Building application..."
      - run:
          name: Simulate publish
          command: echo "Successfully published package (simulation)!"

workflows:
  release:
    when:
      equal: [ "release", << pipeline.parameters.GHA_Event >>]
    jobs:
      - release
