name: Trigger CircleCI on Release

on:
  release:
    types: [published]
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI Pipeline
        id: trigger-circleci
        run: |
          RESPONSE=$(curl -s -X POST \
            "https://circleci.com/api/v2/project/gh/${{ github.repository }}/pipeline" \
            -H "Circle-Token: ${{ secrets.CCI_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "branch": "${{ github.event.release.target_commitish }}",
              "parameters": {
                "GHA_Event": "release",
                "GHA_Actor": "${{ github.actor }}",
                "GHA_Action": "trigger-circleci",
                "GHA_Meta": "${{ github.event.release.tag_name }}"
              }
            }')
          echo "CircleCI API Response: $RESPONSE"
          PIPELINE_ID=$(echo "$RESPONSE" | jq -r '.id')
          if [ "$PIPELINE_ID" != "null" ] && [ -n "$PIPELINE_ID" ]; then
            echo "Successfully triggered pipeline: $PIPELINE_ID"
          else
            echo "Failed to trigger pipeline"
            echo "$RESPONSE"
            exit 1
          fi
