name: Trigger CircleCI on Release

on:
  release:
    types: [published]
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI Pipeline
        id: trigger-circleci
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
          TARGET_BRANCH: ${{ github.event.release.target_commitish }}
