name: Trigger CircleCI on Release

on:
  release:
    types: [published]
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI Pipeline
        id: trigger-circleci
        run: |
          RESPONSE=$(curl -X POST \
            "https://circleci.com/api/v2/project/gh/${{ github.repository }}/pipeline" \
            -H "Circle-Token: ${{ secrets.CCI_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "branch": "${{ github.event.release.target_commitish }}",
              "tag": "${{ github.event.release.tag_name }}",
              "parameters": {
                "GHA_Event": "release",
                "GHA_Actor": "${{ github.actor }}",
                "GHA_Action": "trigger-circleci"
              }
            }')
          echo "CircleCI API Response: $RESPONSE"
          echo "$RESPONSE" | jq -e '.id' > /dev/null || (echo "Failed to trigger pipeline" && exit 1)
